### PR TITLE
Add new regions

### PR DESCRIPTION
**Pull request by nguyenchr**
https://aussiecommerce.atlassian.net/browse/LENG-830

New regions we are targetting for mastercard partnership!!

### CODE REVIEW

**Comment by eddiemcleanlux** [comment]
@mastfissh Should/could we refactor things in payment service to use lib-regions rather than defining its own contants/enums? Or are there reasons why that's not feasible?

**Comment by mastfissh** [comment]
How would the postgres database read those values?

**Comment by eddiemcleanlux** [comment]
It could update the enum from lib-regions on every deploy using [this](https://blog.yo1.dog/updating-enum-values-in-postgresql-the-safe-and-easy-way/) method. Just a thought. Might be more trouble than it's worth.

**Comment by mastfissh** [comment]
I think there's an extremely high risk of that kind of automation going horribly wrong...

**Comment by eddiemcleanlux** [comment]
Yeah, probably.

**Pull request merged**
